-- Create admin user for testing
-- Note: This creates a user in auth.users with admin/admin credentials
-- The password will be hashed by Supabase

INSERT INTO auth.users (
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  confirmation_token,
  recovery_sent_at,
  recovery_token,
  email_change_sent_at,
  new_email,
  email_change_token_new,
  email_change_token_current,
  new_phone,
  phone_change_sent_at,
  phone_change_token,
  created_at,
  updated_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  phone,
  phone_confirmed_at,
  phone_change,
  email_change,
  email_change_confirm_status,
  banned_until,
  delete_at
) VALUES (
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'admin',
  '$2a$10$GFDJKs5w8PQYcHKwqqQyGue1EnO2AmqHZ1FKrWmuRHhd5Rk.bR7Ka', -- This is 'admin' hashed with bcrypt
  now(),
  now(),
  '',
  null,
  '',
  null,
  '',
  '',
  '',
  null,
  null,
  '',
  now(),
  now(),
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"name": "Admin User"}',
  false,
  null,
  null,
  '',
  '',
  0,
  null,
  null
) ON CONFLICT (email) DO NOTHING;